### ISSUE TITLE
DMPTool image for IdPs missing

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#126]
There is an image for the DMPTool that shows up in institutions' IdPs. I supposed it's configured in the Incommon metadata. It is supposed to be here:
https://dmp.cdlib.org/img/dmptool_logo.svg

Just a broken link now.

**Comment by briri** [comment]
@mxsstrong can you update the incommon metadata for us. I think the name of the file may have changed since we first spoke of it.
Use: https://dmptool.org/images/DMPTool_logo_blue_shades_v1b3b.svg

If the Incommon site doesn't size it appropriately, you can use one of the others maybe on the Promote page: https://dmptool.org/promote

**Comment by stephaniesimms** [comment]
waiting to do incommon metadata updates all together after we decommission the older servers while doing cleanup

**Comment by mxsstrong** [comment]
I updated this in dev environment to ensure that the svg image works properly.  I also created a pivotal ticket to track the work to coincide with the decommissioning of the old servers. https://www.pivotaltracker.com/story/show/156137839
