### ISSUE TITLE
E-Mail text on DMP submitted for Review: allow admins to customize message

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#139]
From Chris Eaker, University of Tennessee:

When someone submits a plan for review, do they get a notification from the system that it was submitted? If so, what does it say? It would be nice to be able to customize that notice and say something about how long it will take to review or whatever.

**Comment by stephaniesimms** [comment]
Nora Mattern from Pitt +1 for customizing text:

It would be useful for them to know that the informal review is being conducted by the library and to give the submitter a sense of the turn around time.

**Comment by mxsstrong** [comment]
the reviewer and/or the submitter/collaborators on the plan can have a dialog using the comment feature.    The owner comment section are only for collaborators where as the reviewers comments goes to everyone involved in the plan, including reviewers and collaborators.  Let me know if this response doesn't address your issue.

**Comment by mxsstrong** [comment]
Example test for a plan would look like:

Hello [Plan Owner],

The DMP "test 2: review functionality" has been submitted for institutional review.

If you have questions pertaining to this action, please visit the Review DMPs page at https://dmptool.org/plans/XXXX/perform_review

You may change your notification preferences at https://dmptool.org/users/XXXX/edit#tab_tab2 .

Please do not reply to this email.

You may always visit our contact page at https://dmptool.org/contact

**Comment by stephaniesimms** [comment]
Admins would like to have the ability to customize the auto-generated email. That way, when a researcher submits a plan for review they have a clear idea about who it's been submitted to and when they can expect a reply.

**Comment by mxsstrong** [comment]
A plan is submitted and an auto-gen email is sent to the Admin/Reviewer that a plan has been submitted.  It is AFTER this action takes place that an Admin/Reviewer could respond to the researcher when they might expect a reply.  This can occur easily with a follow up review comment.  

The email that is sent out at time of submission could not realistically be configured ahead of time noting how long it will take to review a plan.  By following the link in the email to perform the review, the Admin/Reviewer could add the comment which would be emailed to the user.

Example of comment emailed:
Hello [Plan Owner],

[Admin/Reviewer] has commented on the plan "Copy of mxs test" :

This plan will be reviewed in 10 days

If you have questions pertaining to this action, please visit the DMP Overview page at https://dmp2-staging.cdlib.org/plans/1422/edit

You may change your notification preferences at https://dmp2-staging.cdlib.org/users/14/edit#tab_tab2 .

Please do not reply to this email.

You may always visit our contact page at https://dmp2-staging.cdlib.org/contact

**Comment by elisedunham** [comment]
I'd like to express a +1 for customizing the text for the immediate confirmation email to plan owners. It is possible for us to include information on turnaround time because it is a commitment we make publicly. Here is an example of the kind of information that I would like to include:

Hello [Plan Owner],

Thank you for submitting your DMP for institutional review. The Research Data Service team at the University Library will review your DMP within 1-2 business days. 

Sincerely,
Research Data Service
[RDS email]

If you have questions pertaining to this action, please visit the DMP Overview page at https://dmp2-staging.cdlib.org/plans/1422/edit

You may change your notification preferences at https://dmp2-staging.cdlib.org/users/14/edit#tab_tab2 .

Please do not reply to this email.
