### ISSUE TITLE
Template status listed incorrectly

### ISSUE THREAD

**Issue by amyehodge** [CDLUC3/dmptool#146]
If you click on the customize option for a template but do not actually make any customizations, the template is then listed in the table as having unpublished customizations, even though it doesn't. This should still be listed as "Not customized." This is now the case for the GoMRI 2018 template for me. I prefer not to click publish on this because it becomes confusing regarding which have been published and which haven't if I do that.

**Comment by stephaniesimms** [comment]
@amyehodge - this behavior is attributable to a problem with template versioning, which we're refactoring now. at the moment the system creates a new version every time you open a template, even just to view it. once the refactoring is done admins will be able to open a template without affecting the status (you won't have "unpublished customizations" unless you actually create some).

in the meantime, it makes no difference whether you "publish" the customizations or not since there is nothing there to publish. to keep the tally of customized templates accurate, you can continue to not publish. after the versioning work is done, we can review the tallies and do any necessary clean-up so they reflect an accurate number of customized templates.

the work is halfway done and fixes should be in place at the end of our next sprint (ca. 3 weeks)

**Comment by amyehodge** [comment]
Thanks for the explanation, Stephanie. Glad I'm not picking up too many brand new problems you weren't already aware of and planning for.

**Comment by stephaniesimms** [comment]
this is fixed as part of template refactoring https://github.com/DMPRoadmap/roadmap/releases/tag/v1.1.0
changes will be deployed to dmptool service next week with comms to notify users
