### ISSUE TITLE
Orgs should appear in list of Participating Institutions

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#162]
Orgs like UCAR, PEER, etc should appear in the Participating institutions list https://dmptool.org/public_orgs

they are available to users for selecting login affiliation. everything in this list should be displayed in the table above.

**Comment by briri** [comment]
This is because UCAR and PEER are defined as both funders and institutions.
![screen shot 2018-05-30 at 8 53 01 am](https://user-images.githubusercontent.com/1204467/40731903-f5eba990-63e6-11e8-9ab5-cded87e64020.png)

We explicitly block funders from appearing in that list. They seem to have templates, so I'm guessing that designation is appropriate. I can ease the restriction to show 'funder only' Orgs like Sloan, DOE, etc. but this would allow USGS to appear in the list since they have a multi-org type designation as well

**Comment by stephaniesimms** [comment]
they're actually both Orgs, not Institutions. We can maybe remove the funder type...will test and see if that meets all needs.

**Comment by briri** [comment]
ok. will update to always show an 'Organization' or 'Institution' regardless of whether they are also a 'funder'

**Comment by stephaniesimms** [comment]
all Orgs and Institutions appear in the list that should now. closing.
