### ISSUE TITLE
tinymce editors for comments missing lists and tables

### ISSUE THREAD

**Issue by stephaniesimms** [CDLUC3/dmptool#177]
the tinyMCE editors appear to be standardized everywhere except lists and tables are missing in the Comments area on the write plan page. this is only happening on dmptool stage, not roadmap stage.

![tinymce](https://user-images.githubusercontent.com/12703638/41681251-e22194c6-7488-11e8-929f-fb8afda789f2.png)

**Comment by briri** [comment]
this is related to https://github.com/DMPRoadmap/roadmap/issues/1594.

We weren't happy with the resolution for that one. My suggestion is to update the notifications page so that its Tinymce editor allows tables and lists. We can just rely on Super Admins not to use that functionality since it will not display properly. That should become evident pretty quickly if they do use it.

**Comment by stephaniesimms** [comment]
transferred to roadmap
