### ISSUE TITLE
Not all plans reported for institution via API

### ISSUE THREAD

**Issue by amyehodge** [CDLUC3/dmptool#181]
These two API searches via web browser include the same list of plans for Stanford:
https://dmptool.org/api/v1/plans
https://dmptool.org/api/v1/plans_full

However, as the admin for Stanford when I log in and look at "Review DMP" page, I can see additional plans that I have reviewed that are not included on this list. I have attached a screenshot. Only the one by Joan Bresnan appears in the API output.

![screen shot 2016-04-12 at 9 50 09 am](https://cloud.githubusercontent.com/assets/5558511/14468363/2917cc3a-0094-11e6-9f3b-4209838add5d.png)

[Full_plans.xlsx](https://github.com/CDLUC3/dmptool/files/215522/Full_plans.xlsx)
[List_of_Plans.xlsx](https://github.com/CDLUC3/dmptool/files/215523/List_of_Plans.xlsx)

It seems that the API is not finding all the relevant plans.

**Comment by stephaniesimms** [comment]
This is happening because we don't provide info about Private plans via the API, however, admins can see Private plans in the UI when the plan owner requests feedback (submits the plan for review). 

We're updating the privacy policy text (not the policy itself) and language in the tool to make it clear to users that we can/will provide info about Private plans to authorized users (institutional admins) for business development purposes. Once we clarify the privacy policy, we will amend the API calls to return info about all plans (going forward), regardless of visibility setting. The goal is to provide more robust usage info. These changes should be in place by next month.

**Comment by amyehodge** [comment]
Great! Thanks for the explanation!
