### ISSUE TITLE
Determine messaging for the new DMP ID (DOI) feature

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#217]
Below is the messaging a user will see on the Finalize/Pubish tab if they have not met all of the requirements to 'Register' their DMP:
<img width="1309" alt="Screen Shot 2020-10-05 at 11 56 10 AM" src="https://user-images.githubusercontent.com/1204467/95136152-75b0d780-071a-11eb-88b1-663a30cd5541.png">

Below is the messaging a user sees once they have met all of the requirements to 'Register' their DMP:
<img width="1294" alt="Screen Shot 2020-10-05 at 1 49 58 PM" src="https://user-images.githubusercontent.com/1204467/95136163-79445e80-071a-11eb-8404-a0e4051d264e.png">

Below is the error message a user will see should an error occur within the DMPHub or EZID and the DMP ID could not be registered (e.g. EZID is down)
<img width="1293" alt="Screen Shot 2020-10-05 at 11 56 38 AM" src="https://user-images.githubusercontent.com/1204467/95136168-79dcf500-071a-11eb-8611-e513690e64a3.png">

Below is what the user will see on the Finalize/Publish tab once their DMP has been 'Registered'
<img width="1300" alt="Screen Shot 2020-10-05 at 1 50 28 PM" src="https://user-images.githubusercontent.com/1204467/95136160-78abc800-071a-11eb-9036-8291fb2200b0.png">

**Comment by mariapraetzellis** [comment]
I have put in new text for the DMP ID feature in this google doc: https://docs.google.com/document/d/1oOx1yCqJR-VQNP7MFF75H31qC-Q28jolzhGeIZjjavA/edit

**1.  if they have not met all of the requirements to 'Register' their DMP:**

Register your plan

Get a **DMP ID** [LINK https://github.com/CDLUC3/dmptool/wiki/Networked-Data-Management-Plans-(maDMPs))  for your data management plan. 

ADD A NEW TOOL TIP: DMP IDs track connections between your DMP and research outputs such as datasets and articles. 

In order to register your plan you must have completed the following: 

- answered at least 50% of questions
- identified your funder 
- defined at least one contributor with an ORCID and an affiliation 

Once the steps above are satisfied, a button to register your plan will appear here. 

**2. Below is the messaging a user sees once they have met all of the requirements to 'Register' their DMP:**


Get a **DMP ID**  [LINK https://github.com/CDLUC3/dmptool/wiki/Networked-Data-Management-Plans-(maDMPs)) for your data management plan. 

ADD A NEW TOOL TIP: DMP IDs track connections between your DMP and research outputs such as datasets and articles

Button reads: “Register” Button should be blue to match our other buttons 

**3. Below is what the user will see on the Finalize/Publish tab once their DMP has been 'Registered'**

Your plan has been registered. Your DMP ID is xxxx. [Once we have connections with data repositories we will add text here instructing users how to utilize their ID]

**Comment by mariapraetzellis** [comment]
Need to review and make sure staging reflects the current messaging (DMP ID). I will review text we have on the page when minting an ID. Erin should also take a look at this for clarity.
