### ISSUE TITLE
Global plan status cleanup for plans created prior to v3 (esp to flag test plans)

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dmptool#238]
Janice Masud-Paul from Drexel writes:

We have plans that are more than a year old that are empty or obviously tests visible to the entire organization. I would like to make them private.

**Comment by marisastrong** [comment]
Seems like instead of private, they should be set as test plans.

**Comment by briri** [comment]
Agree with @marisastrong.
Org admins don't have a way to change the visibility on behalf of their users. If you can get a cutoff date, we can look into doing a bulk update on the DB.

**Comment by cpwillett** [comment]
Is there a reason admin couldn't have the functionality to do it themselves?

**Comment by stephaniesimms** [comment]
I agree that these should be set to test plans and we can do a global cleanup for org and public plans. Cutoff date should be migration to the new version of the tool. Since then we haven't had issues with test plans in the public list because we implemented the 50% questions answered threshold to change the visibility to org or public.

Our terms of use and privacy policies state that plan owners have control over their plans. We provide admins with insight into plans created by users at their institutions for program dev purposes.

@briri we can figure out a global cleanup to switch status of plans created prior to 28Feb2018 with:
- "test" in the title
- < 50% questions answered
- anything else?

**Comment by briri** [comment]
sounds good @stephaniesimms I will plan to run this as part of the next deploy. Will collect the list or affected Organizations and Plan titles when I run it.

**Comment by briri** [comment]
The query has been run. I marked any plan with the word 'test' in the title that had not been updated since 2/1/18 as test.

Will post the list of affected records on slack

**Comment by stephaniesimms** [comment]
it's fine that test plans remain in the org admin plans table now that they're labeled appropriately. and the roadmap issues you just finished related to calculating usage stats should remedy any other associated problems.

can you also mark any blank plan (no questions answered) that has not been updated since 2/1/18 as 'test'? i think it's safe to assume that these are also test plans. this should go a long way in cleaning up stats and addressing the original issue of decluttering org plans lists.

**Comment by briri** [comment]
done. updated any plan that had no questions answered and had not been updated since the migration 2/1/18

**Comment by stephaniesimms** [comment]
reviewed csv and test plan status changes look good. closing.
