### ISSUE TITLE
Funder field should be repeatable

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#303]
We've had a request from an admin to make the Funder field on the project details page repeatable since many of their projects have multiple funding sources. I also think this will be applicable for FAIR Island researchers, as they may also have multiple funding sources behind their research being hosted at the field stations.

**Comment by briri** [comment]
This will take some significant refactoring. We will need to:
- [ ] change the association between Plan and its current `funder_id` and `grant_id`. Might be worth building out a new Funding model so that we have a one to many relationship for Plan -> Funding and a one to one for Funding and its affiliation and grant ids. This would mimic the RDA common standard structure as well
- [ ] need a migration script to move the existing data into the new structures
- [ ] need to update the exports to pull in the correct data
- [ ] need to update API V1 and V2 to work with the new structures. This will be needed for both reading and creating via the API

**Comment by briri** [comment]
decided not to work on this now
