### ISSUE TITLE
RORs for field stations in FAIR Island DMPs

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#305]
To make sure the field station ROR makes it into the metadata we’re sending to DataCite, we need to hardcode it so that any DMPs coming from FAIR Island partner sites (Tetiaroa Society) have hardcoded ROR IDs that will be automatically pushed to the DMPHub. We’re still determining if this will be under Contributor> Sponsor or Funding Source.

This will be in the backend since it will only affect a small number of DMPTool users. However, we may need to revisit our approach in the future if we identify further uses for this. 

We will need to add this to the database, update the JSON interaction, and have the DMPHub send this to the appropriate location in the EZID record.

**Comment by briri** [comment]
We want to define field stations as contributor entries in the schema:
```
  name="Tetiaroa ...",
  nameType="Organizational",
  contributorType="Sponsor",
  nameIdentifiers: [ ... ROR ... ]
```

For Dataset related works discovered via the API, we should use the `Documents` relation type.

We should stop using the 'IsMetadataFor' related identifier since the DMP ID already resolves to the landing page and the link back to the PDF is found there if it is publicly visible.

For all other related works manually added by a user we should: ???

**Comment by briri** [comment]
Added research station to the RDA common standard as the new `dmproadmap_sponsors` array:
<img width="757" alt="Screen Shot 2021-12-02 at 1 42 59 PM" src="https://user-images.githubusercontent.com/1204467/144507885-6c69d522-f239-45b7-a70c-7a2fc78b3795.png">

We need to update the DMPHub to include a resourceTypeGeneral attribute to the Datacite XML that specifies the type of each related identifier

**Comment by briri** [comment]
Updated DMPHub to pass the sponsor through to DataCite:
<img width="887" alt="Screen Shot 2022-03-01 at 10 53 25 AM" src="https://user-images.githubusercontent.com/1204467/156230960-1a6686ba-b9a9-4d63-9b5a-1679c3e7081f.png">
