### ISSUE TITLE
Remove ability for users to manually add related works

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmptool#315]
Remove ability for users to add related works but still allow API to add them.

Continue displaying the citations in read only format though

**Comment by Br-Johnson** [comment]
I'm just wondering if this is going to impact my plan to use the DMPTool as a way of linking datasets and articles by 'manually adding related works' through the DMP tool. 

I'm assuming this issue will remove the '+ add a related works' button on the Project Details tab. Just curious why this is being removed? Is it so that references to the DMP have to be directed from external DOIs that point to the DMP as a related works?

The reason I ask is that I was going to create an issue indicating that the relatedIdentifierType field in the XML for the DMP is showing all my DOIs as a 'handle' which is preventing accurate citation and connections using GraphQL... But perhaps its moot if this feature of the DMP is going away? Thanks in advance for your help and information, and all the great work on the DMPToool.

**Comment by briri** [comment]
Hi @Br-Johnson we're planning on disabling it at the moment because we're finding that researchers are using it in unexpected ways.

Our primary use case within the DMPTool is for users to create a DMP as part of their grant application process (funders like NIH, NSF, NASA, etc.). They're created long before any resulting research outputs are generated and users rarely return to the site afterward.
 
We first introduced this functionality as a way to display dataset DOIs we 'learn' about from external systems like RSpace or Dryad. We then discovered a need to collect the identifiers of works that the user would be basing/deriving their research from (e.g. someone doing computational analysis of large datasets generated as part of another project). 

We're now organically discovering new use cases (e.g. users are providing us with their proposed bibliographies for their eventual publications) and finding that we can't accurately determine/convey the relationships the DMP has to these items.

There are several routes we may take to support this going forward. The simplest would be to just add some text to the page that explains the use case(s) we're after. A more complex solution may be to provide the user with the ability to identify how the work is related to the DMP (e.g. cites, references, etc.) or allow an organizational admin some sort of curatorial way of making these connections.

As for your concerns about the relatedIdentifierType in the XML, we're actively working with DataCite on a project, https://datacite.org/fair-workflows.html, to determine best practices for conveying relationships between a DMP and works generated as the result of the corresponding project. You can find some discussion of this in the comments on issue #305 (I think this issue may be of general interest to you as well).

This is all new territory for us so any suggestions you may have would be appreciated.

**Comment by briri** [comment]
@Br-Johnson as an accommodation we are going to allow organizational administrators to continue adding/removing related works until we come up with a suitable long term strategy

**Comment by briri** [comment]
deployed to production in early Dec. 
administrators still have the ability to add related works
