### ISSUE TITLE
Downloaded docx plans throw an error 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#377]
A few users have reported that they get an error when trying to open DMPs that were downloaded as docx files.

For example, when downloading this plan: https://dmptool.org/plans/82519, the user gets the error below when trying to open the word file:
![qXH99MDYAkTaZWD2azYL-Y1TJ7sdp0fHIw](https://user-images.githubusercontent.com/27511575/191128176-511a37bc-d1d9-47a5-b39a-0621ce2b8169.png)

**Comment by briri** [comment]
Seems to be related to the specific version of the NIH template that was used to create that plan. I just created one from the latest and it downloads without issue. Probably a weird (non-ascii character) causing an issue with the HTML -> DOCX conversion.
Will need to compare the question text between versions to confirm.

**Comment by briri** [comment]
I cannot determine why this particular docx fails to open in MS Word. 

OSX Preview and TextEdit, Slack are able to render it. Google docs is able to import it. 

MS Word for Max v 16.65 throws a:
<img width="258" alt="Screen Shot 2022-09-27 at 9 31 34 AM" src="https://user-images.githubusercontent.com/1204467/192583245-891dc1e1-2fa8-462a-939a-05e6398fcc2a.png">

When attempting to 'recover' the docx as suggested, the 'repaired' file is binary and unreadable
<img width="692" alt="Screen Shot 2022-09-27 at 9 32 51 AM" src="https://user-images.githubusercontent.com/1204467/192583455-988c8c0e-b524-43f7-ae14-44565f266f7c.png">

The corrupt docx opens if you export it without the question text. The original suspicion was that the issue lied with the bulleted (unordered) lists on the last few questions. This does not seem to be the case though after further research

I have created a DMP based off of the current NIH template and it has no issues. I created and published a sample template (as a UCOP admin) that contains bulleted lists. The docx for a DMP created from that sample template opens without issue.

There do not appear to be any readily available docx debugging tools available. I found a few possible options (e.g. this [VB.Net one](https://learn.microsoft.com/en-us/office/open-xml/how-to-validate-a-word-processing-document?redirectedfrom=MSDN) but they all require you to have a Windows environment) all comments on StackOverflow with regard to these solutions indicate that there's less than a 50% chance they'll tell us what's actually wrong.

A docx file is actually just a zip archive. If you change `.docx` to `.zip` and then unzip it you can access all of the XML files that make up the document 🤯 
<img width="588" alt="Screen Shot 2022-09-27 at 9 40 38 AM" src="https://user-images.githubusercontent.com/1204467/192585708-166e03b3-f9d6-4a3c-a125-b31f24581921.png">

A comparison of each file between the corrupted docx and the valid ones (both the latest NIH template and my sample template) show NO difference except for the content of the `document.xml` which is expected since the question text is different. All class/xml element name, attributes, document structure, etc. are the same.

Not sure what else to do here. It seems to be an issue in my opinion with MS Word and perhaps just specific versions. 🤷🏻‍♂️ 

There are plans in the system based off of this template that generates corrupted docx files. Around 60-70% of those appear to simply be tests (based on the 'test' flag or the plan names). I also suspect that few users export to docx.

Possible solutions would be to:
- Downgrade the `htmltoword` gem and see if it helps. Issue here is that the current version was released in 2019, so its unlikely to help unless this issue has been present for several years.
- Add some text to the 'Download' page that suggests that users import the docx into Google docs if they have trouble opening it
- Ignore it since the latest version of the template exports docx without any issues

**Comment by briri** [comment]
another option may be to export as an OpenOffice doc format

**Comment by briri** [comment]
related to https://github.com/DMPRoadmap/roadmap/issues/3221
