### ISSUE TITLE
Make several default templates available in dmptool

### ISSUE THREAD

**Issue by fcsousaunifesp** [CDLUC3/dmptool#480]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (v4.0.9)**

Good afternoon, I'm working on a dmptoll fork, and I've created a model that I would like to be available in my application,for each and every user, as the default template.
Could you tell me what the procedures are? Informing what I need, in this case it is possible to include, later some other models that I am creating, and that these can be made available as standard, repeating, for each and every user, as the default template..

Thanks a lot!

**Comment by briri** [comment]
Hi @fcsousaunifesp 

The code currently only supports a single default template. This is set via the `is_default` flag in the `templates` table.

After a user specifies their research institution and funder on the 'Create Plan' page, [this code in the template_options_controller.rb](https://github.com/CDLUC3/dmptool/blob/6f9a7eca9297d9c00bddc8109fc0ec72fcae9b86/app/controllers/template_options_controller.rb#L57) is executed. This is where the default template is pulled in. 

You should be able to update the logic in your fork to load multiple templates instead of just one. To do that you will have to update:
- The `app/models/template.rb` to return multiple templates [from the 'default' method](https://github.com/CDLUC3/dmptool/blob/6f9a7eca9297d9c00bddc8109fc0ec72fcae9b86/app/models/template.rb#L277)
- Verify that the [latest_customisable scope in the templates.rb model](https://github.com/CDLUC3/dmptool/blob/6f9a7eca9297d9c00bddc8109fc0ec72fcae9b86/app/models/template.rb#L232) still works as expected.

If you do modify your code, please consider sending us a PR. I think the change sounds like it would be useful :)
