### ISSUE TITLE
 Integrate  DMPTOOL with RSPACE.

### ISSUE THREAD

**Issue by fcsousaunifesp** [CDLUC3/dmptool#496]
Good morning team.
Could you tell us which path you took to integrate  DMPTOOL with RSPACE.
Can you tell us about the technological requirements, and what are the documentary requirements, for this integration?
This is my version DMPRoadmap code v4.0.9, and this is my url, https://pgd.ibict.br

Best regards

Flavio Castro de Sousa

**Comment by briri** [comment]
Hello Flavio,

You will want to contact RSpace (if you have not already) and have them add your system to their list of approved integrations (they need a logo, the URL and API, etc.). For example, this is what our's looks like:
<img width="599" alt="Screenshot 2023-07-28 at 9 08 41 AM" src="https://github.com/CDLUC3/dmptool/assets/1204467/6bd150bf-7525-4d2d-9056-66a71c670760">

RSpace uses the API v2 endpoints to tie into the system. You will need to have them create a user account and then go to the Profile -> Developer Tools page where they can enter their information to create their API credentials. They will need to provide a Redirect URI for the Oauth2 workflow to work! They've connected to ours, so they are familiar with the process.
<img width="387" alt="Screenshot 2023-07-28 at 8 59 49 AM" src="https://github.com/CDLUC3/dmptool/assets/1204467/cbc22c21-4b13-420c-9b19-de32f86a2a19">

Once they have created their credentials they will be given the ability to read DMPs. If you want them to be able to send you dataset DOIs so that they get connected back onto the DMP record, you will need to manually give them permission to do that in the database. You can do that by updating the `UPDATE oauth_applications SET scope = 'public read_dmps edit_dmps' WHERE id = [their id];` to their record.

I recommend having them do this in a stage/test server first before giving them access in production so that you can verify everything is working as expected.

For reference:
- RSpace demo of the integration: https://www.youtube.com/watch?v=dIsYLcx6qNc&ab_channel=ResearchSpace
- RSpace documentation on how their users connect their RSpace account to your system. https://researchspace.helpdocs.io/article/o0wlhlgxnr-dmptool-integration
- I have another Ruby/Sinatra application that was written to help test your API. If you are interested, you can find it here: https://github.com/DMPRoadmap/api_tester 
  - You will need to create a your own test user credentials in the Developer Tools section. Use `http://localhost:4567/oauth2/callback` as the Redirect URI. Don't forget to give yourself permission to edit (see SQL above)
  - Run `ruby api_test.rb` to start the application and then go to `http://localhost:4567` Enter the URL of the system you want to test and then select API v2. 
  - Then enter your test user's id and secret and try the different buttons. If it works you will see a success message at the top and results at the bottom. If it fails you will see a nasty error message (check the DMP system logs for the issue). The top section uses the OAuth2 `client_credentials` workflow to access Public DMPs. The bottom section uses the OAuth2 `auth_code` workflow which will ask you to login (if you are not already logged in on that browser) and then authorize the connection. If the authorization works, it will perform whatever action the button is for (e.g. fetch the DMP PDF)
