### ISSUE TITLE
Clicking on a super admin user profile gets 500

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#576]
To reproduce: 

- Log in as a Super Admin
- Go to the Users table
- Search for a super admin (Maria Praetzellis, Brian Riley, Erin Robinson...) 
- Click on either the Plans or Name links
- This goes to a 500 

I think this only happens for super admins. I am able to access these pages for DMP Tool admins & users successfully.

**Comment by bofstein** [comment]
Brian suspects a field in the database causing it, need to check the error logs

**Comment by bofstein** [comment]
Happened to me on one of my alt accounts as well which isn't a Super Admin, though it's possible the account was in the past.  I noticed the URL has `super_admin` in it when I click.

![Image](https://github.com/user-attachments/assets/83ee0414-6e8e-4b8a-bb69-c919edf744cd)

![Image](https://github.com/user-attachments/assets/cf565549-ba97-4154-9f9d-a2b4a567eb77)

**Comment by briri** [comment]
Here is the error I see running locally.

![Image](https://github.com/user-attachments/assets/3ebcd796-8915-4637-ae74-a8e3df5e3fb5)


When building out phase one of the pilot, we converted `plan.dmp_id` to just be a field on the `plans` or `drafts` table instead of a reference to a joined table `identifiers`. I think we just missed the edit user page when making that change.

**Comment by briri** [comment]
did some testing in stage and it appears to be fixed now. Will plan to deploy to prod early next week
