### ISSUE TITLE
'Upload plan' feature does not allow you to enter information for 'License for reuse:'

### ISSUE THREAD

**Issue by magicalmary** [CDLUC3/dmptool#579]
'Upload plan' feature does not allow you to enter information for 'License for reuse:'

1. Go to landing page:  https://dmphub.uc3prd.cdlib.net/dmps/10.48321/D1B581751F
2. User sees empty field for "License for 
![Screenshot 2024-04-29 at 3 02 03 PM](https://github.com/CDLUC3/dmptool/assets/84808621/9a48072d-6e87-4f19-bd3f-27f4810039fb)
reuse:'
3. Go to 'Upload plan' table and click to 'update' the same project
4. Click on 'Research outputs'
5. Click on Edit for the one output listed.
![Screenshot 2024-04-29 at 3 08 34 PM](https://github.com/CDLUC3/dmptool/assets/84808621/63f16e01-9f89-4ba4-90c4-528b2554f06a)

**Expected behavior**
The field to enter 'License for reuse' is shown for data entry.

**Actual behavior**
There is no field to enter info for the 'License to reuse'

**Comment by bofstein** [comment]
On the regular tool, if there's no license entered it seems to just not show that field.  Rather than add the field to the pilot project when it's likely not needed yet, we're doing to match that functionality so it doesn't appear blank.  If there is a need in the future to have this for the pilot we can revisit.

**Comment by bofstein** [comment]
Deleted my incorrect comment.  Currently on the regular site, the License field shows up only if a Repository is selected, whether or not the License is filled out.

For both the Pilot Project and Live site, it would be better to make it so that if there is no License entered, that field does not appear on the landing page.  Then for the Pilot, we can continue to not ask that question (unless a specific need comes up for it), and it will be less confusing on the landing page.

Acceptance criteria:
- For any DMP (pilot upload or regular) that has a License entered, the license appears on the landing page
- For any DMP (pilot upload or regular) that does not have a License entered, the license field does not appear on the landing page.

**Comment by briri** [comment]
Ah, this is because of the structure of the [RDA Common Standard for DMPs](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard) which has the license as part of the `distribution` and not the `dataset`, so it is linked to the repository where the item will be deposited. Not sure if it makes sense or not, I think some repositories require different license types (maybe GDPR vs US) 🤷🏻‍♂️. 

We should consider this in the new system when we go to build the research outputs page.
