### ISSUE TITLE
DMPHub communication not processing 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#598]
DMPHub communication has been queueing up and not processing. Brian thinks this may be due to server patching. 

 For example, 101113 with a DMP ID: 10.48321/D1WK99. The Funding status was changed from Aproved to Denied. A URL in the Grant ID field was also removed. Neither of these changes are viewable from the[ landing page. ](https://dmphub.uc3prd.cdlib.net/dmps/10.48321/D1WK99)

**Comment by briri** [comment]
The recent Ruby upgrade involved the installation and use of rbenv to manage our Ruby environment. As part of the upgrade process we neglected to update the systemctl unit file for delayed_job and did not restart the servers. 

The server was restarted after the most recent OS patching cycle which meant that delayed_job needed to startup and was unable to because we did not update the systemctl unit file.

@ashleygould patched this morning and delayed_job has finished processing all of the queued activity
