### ISSUE TITLE
RORs pointing the the wrong organization

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmptool#637]
It looks like the RORs of some contributor affiliations are pointing to the wrong ROR. 

All of the contributors to the Moorea Biocode DMP are pointing to UC Berkeley https://dmphub.uc3prd.cdlib.net/dmps/10.48321/D1F88S 

For the EAGER grant, they are all pointing to the UCOP ROR https://dmphub.uc3prd.cdlib.net/dmps/10.48321/D17598

In both examples, the correct affiliation is listed on the DMP ID landing page, but the corresponding ROR ID is either UC Berekely (for Moorea Biocode) or UCOP (for our EAGER)

**Comment by briri** [comment]
I was able to fix this by adding myself as a collaborator on these 2 DMPs and then going into the DMPTool, adding a blank space to the end of the abstract, and then saving (on both plans). This forced an update to the DMPHub which now has the correct ROR ids.

This unfortunately creates a new "version" in the DMPHub, but I guess that makes sense since we have updated/fixed the ROR ids.

I'm not sure why it happened, my suspicion is that it has been that way for a while ... at least since the last updates to the DMPs in January.
