### ISSUE TITLE
[Spike] - Rails 6.1 has reached End of Maintenance and needs to be upgraded to 7.2

### ISSUE THREAD

**Issue by jupiter007** [CDLUC3/dmptool#656]
There was some info shared on the #dmptool Slack channel that the Merritt team discovered Rails 6.1 has reached End of Maintenance.

Ruby on Rails, https://rubyonrails.org/2024/10/15/new-maintenance-policy-and-eol-annouments, announced that  Rails is providing one last security release for 6.1, and that it's crucial to upgrade to a supported version, 7.2, as soon as possible.

**Comment by briri** [comment]
DMPOpidor has upgraded their fork of the DMPRoadmap codebase to 7.1. There is an outstanding PR in the shared repo we can use as reference: https://github.com/DMPRoadmap/roadmap/pull/3426/files

**Comment by bofstein** [comment]
This ticket is just investigation of what's needed for now, will make additional tickets for the work once that's done

**Comment by briri** [comment]
Did some reading of the official Rails upgrade guide for [6.1 to 7.0](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-6-1-to-rails-7-0) and noted the following:
- We will need to update a few occurrences of `button_to`
- We may possibly need to add `sprockets-rails` to the Gemfile. See if its necessary by running `rails assets:precompile` without it first
- may need to implement a cookie rotator due to a change from SHA1 to SHA256 [See the docs](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#key-generator-digest-class-change-requires-a-cookie-rotator)
- Update the ActiveSupport cache support config
- Thoroughly test logo uploads and PDF generation. There are a lot of ActiveStorage changes. Nothing jumps out in the docs but we should be thorough when testing these
- The DB Schema file format has changed, so run a `rails schema:dump` and review

The [7.0 to 7.1 docs](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-7-0-to-rails-7-1):
- Add new secret key base file for dev/test
- Changes to how the autoloader paths are handled, so make sure all modules in the lib and app/services directory load properly
- Update the way `@rails/ujs` is imported for both the standard Rails JS and the React pilot project pages
- ActiveRecord encryption changed form SHA1 to SHA256. Verify that the user passwords are ok
-

**Comment by briri** [comment]
I think a reasonable plan of attack for the upgrade will be to:
- Phase 1
  - Update the Gemfile to Rails 7.2 and then run `bundle install`
  - Review Gems locked to a specific version in the Gemfile and determine if that is still necessary
  - Run `bundle update` and `yarn upgrade` to update all dependencies
  - Fix any errors, deprecation messages or security issues
- Phase 2 
  - Run through the upgrade guides and make necessary changes
  - Review the DMPopidor PR for DMPRoadmap and make corresponding changes in our codebase
  - Startup the app
  - Address any issues that arise on startup
  - Run `rails assets:precompile` to make sure the assets can build
- Phase 3
  - Deploy to stage
  - Manually test everything in the UI
